pipeline { 
    agent none
    stages{ 
        stage('vote_build'){
            agent{
                docker{
                    image 'python:3.9-slim'
                    args '--user root'
                    }
                    }

            steps{ 
                echo 'Compiling vote app.' 
                dir('vote'){
            
                        sh "pip install -r requirements.txt"

                } 
            } 
        } 
        stage('vote_test'){
           
            agent {
                docker{
                    image 'python:3.9-slim'
                    args '--user root'
                    }
                    }
            steps{ 
                echo 'Running Unit Tests on vote app.' 
                dir('vote'){ 
                   
                        sh "pip install -r requirements.txt"
                        sh 'nosetests -v'
                        
                        
                } 
            } 
        } 

      stage('vote_docker-package'){
          agent any
         
          steps{
            echo 'Packaging vote app with docker'
            script{
              docker.withRegistry('https://index.docker.io/v1/', 'Docker_Hub') {
                  // ./vote is the path to the Dockerfile that Jenkins will find from the Github repo
                    def voteImage = docker.build("walterskot/vote:v${env.BUILD_ID}", "./vote")
                    def safeBranch = env.BRANCH_NAME.replaceAll('/', '-')
                voteImage.push()
                voteImage.push(safeBranch)
                voteImage.push("latest")
              }
            }
          }
      }

    } 
    post {
        always{
            echo 'Pipeline for vote is complete'
        }
    }

} 


