pipeline {
    agent any
    tools {
		maven 'maven 3.9.9'
	}
    stages{
        stage('build'){
            steps{
                echo 'building worker app'
                dir('worker'){
                  sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                echo 'Running unit tests on worker app'
                dir('worker'){
                  sh 'mvn clean test'
                }
            }
        }
        stage('package'){
            steps{
                echo 'packaging worker app into a jarfile'
                dir('worker'){
                  sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post{
        always{
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint:  true
            echo 'Building multibranch pipeline for worker is completed.'

    }
  }
}
